sudo: required
language: java
jdk:
- oraclejdk8
services:
  - docker

env:
  COMPOSE_VERSION: 1.8.1

before_install:
 - cd DDIAccessServicesTests
 - pwd
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin
 - docker-compose up -d
 - cd ..
 - pwd


install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- mvn test -B